name: CI - Build & Test (CP2)

on:
  push:
    branches:
      - develop
      - "feature/**"
      - "hotfix/**"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: "maven"

      - name: Maven - Run unit tests
        run: mvn -B -DskipTests=false test

      - name: Maven - Package
        run: mvn -B -DskipTests=true clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar