version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"  # Mapeia a porta 3306 para acessar o MySQL externamente
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u app -papp || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: api
    depends_on:
      - db
    ports:
      - "8080:8080"  # Expondo a API na porta 8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
